theme: minima
title: What you need to know about maps
author: Retha
email: retha@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring maps. You will learn how to make beautiful and informative maps

# social links
twitter_username: retha_maps # DO NOT include the @ character, or else the build will fail!
github_username:  retha_maps # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
